### ISSUE TITLE
yarn build failed 

### ISSUE THREAD

**Issue by yangwao** [patractlabs/redspot-v0.1#8]
Hello, I was trying to go through redspot and it didn't work for me and yield error on `yarn build`

Commands issued before 
```bash
yarn
npx redspot-new flipper
cd flipper/
yarn build
```

![image](https://user-images.githubusercontent.com/5887929/94692974-75d46000-0333-11eb-83aa-7869f0548e42.png)

Happy to chat about smart contracts and Edgeware, please reach me https://t.me/yangwao

**Comment by ii-ii-ii** [comment]
The template currently uses the Ink master branch. Ink has recently been upgraded to 0.3, which caused this error. We have now upgraded the templates of redspot to support ink 0.3. You can reinstall the templates, or update the contract code manually.

**Comment by Robbepop** [comment]
Please note that ink! 3.0 has not yet been officially released. Expect chaos if you make use of it.

**Comment by atenjin** [comment]
@yangwao Hi, thanks for this report. this remind us in future RedSpot version, we should support a way to allow user to use different `cargo-contract` and different template. We would add this feature in future RedSpot.
And by the way, current RedSpot in this repo would be dropped after RedSpot 0.2(https://github.com/patractlabs/redspot-0.2) (redspot-0.2 would be renamed to redspot after release, and current repo would be archived)
So that if you trace our process, we advice you to use our new Redspot 0.2 version and Respot 0.2 release. We sincerely welcome developers to use our RedSpot and make suggestions to help us do better.

@Robbepop and thanks for this! It seems that ink! 3.0 would be released in Sub0 conference this year in October 15th, right? We would make RedSpot to support ink! 3.0 after that time.

**Comment by liuchengxu** [comment]
@yangwao Try to apply the following patch and then you can continue to try out redpot, but expect chaos as mentioned above :).

```diff
diff --git a/lib.rs b/lib.rs
index 277af6b..9e4834f 100755
--- a/lib.rs
+++ b/lib.rs
@@ -2,14 +2,14 @@

 use ink_lang as ink;

-#[ink::contract(version = "0.1.0")]
+#[ink::contract]
 mod flipper {

     /// Defines the storage of your contract.
     /// Add new fields to the below struct in order
     /// to add new static storage fields to your contract.
     #[ink(storage)]
-    struct Flipper {
+    pub struct Flipper {
         /// Stores a single `bool` value on the storage.
         value: bool,
     }
@@ -17,7 +17,7 @@ mod flipper {
     impl Flipper {
         /// Constructor that initializes the `bool` value to the given `init_value`.
         #[ink(constructor)]
-        fn new(init_value: bool) -> Self {
+        pub fn new(init_value: bool) -> Self {
             Self { value: init_value }
         }

@@ -25,7 +25,7 @@ mod flipper {
         ///
         /// Constructors can delegate to other constructors.
         #[ink(constructor)]
-        fn default() -> Self {
+        pub fn default() -> Self {
             Self::new(Default::default())
         }

@@ -33,13 +33,13 @@ mod flipper {
         /// This one flips the value of the stored `bool` from `true`
         /// to `false` and vice versa.
         #[ink(message)]
-        fn flip(&mut self) {
+        pub fn flip(&mut self) {
             self.value = !self.value;
         }

         /// Simply returns the current value of our `bool`.
         #[ink(message)]
-        fn get(&self) -> bool {
+        pub fn get(&self) -> bool {
             self.value
         }
     }
```

**Comment by Robbepop** [comment]
> @Robbepop and thanks for this! It seems that ink! 3.0 would be released in Sub0 conference this year in October 15th, right? We would make RedSpot to support ink! 3.0 after that time.

That is the plan. ;) Let's see how this is going to work out.

**Comment by yangwao** [comment]
Ok now it works, build doesn't fail. 
![image](https://user-images.githubusercontent.com/5887929/94807036-4be07380-03ef-11eb-9869-0fe2f835ecb9.png)
